import { ACHIEVEMENTS } from './config.js';

// ===== GAME STATE =====
export const G = {
    era: 0,
    prestigeLevel: 0,
    starvationAccumulator: 0, 
    res: {
        food: { cur: 0, max: 100, unlocked: true },
        wood: { cur: 0, max: 50, unlocked: true },
        science: { cur: 0, max: 200, unlocked: true },
        stone: { cur: 0, max: 20, unlocked: false },
        clay: { cur: 0, max: 20, unlocked: false },
        skins: { cur: 0, max: 20, unlocked: false },
        copper: { cur: 0, max: 10, unlocked: false },
        coal: { cur: 0, max: 20, unlocked: false },
        iron: { cur: 0, max: 10, unlocked: false },
        tools: { cur: 0, max: 10, unlocked: false },
        steel: { cur: 0, max: 10, unlocked: false },
        faith: { cur: 0, max: 50, unlocked: false },
        gold: { cur: 0, max: 5, unlocked: false },
        lumber: { cur: 0, max: 50, unlocked: false },
        brick: { cur: 0, max: 50, unlocked: false },
        glass: { cur: 0, max: 50, unlocked: false },
        mana: { cur: 0, max: 50, unlocked: false },
        brass: { cur: 0, max: 30, unlocked: false },
        parchment: { cur: 0, max: 30, unlocked: false },
        ale: { cur: 0, max: 40, unlocked: false },
        armor: { cur: 0, max: 20, unlocked: false },
        weapons: { cur: 0, max: 20, unlocked: false },
        chivalry: { cur: 0, max: 10, unlocked: false },
        gunpowder: { cur: 0, max: 30, unlocked: false },
        canvas: { cur: 0, max: 40, unlocked: false },
        art: { cur: 0, max: 20, unlocked: false },
        spices: { cur: 0, max: 30, unlocked: false },
        influence: { cur: 0, max: 10, unlocked: false },
        oil: { cur: 0, max: 50, unlocked: false },
        rubber: { cur: 0, max: 40, unlocked: false },
        plastic: { cur: 0, max: 30, unlocked: false },
        concrete: { cur: 0, max: 50, unlocked: false },
        power: { cur: 0, max: 100, unlocked: false },
        engines: { cur: 0, max: 20, unlocked: false },
        uranium: { cur: 0, max: 10, unlocked: false },
        rocketfuel: { cur: 0, max: 30, unlocked: false },
        superalloy: { cur: 0, max: 20, unlocked: false },
        nanobots: { cur: 0, max: 10, unlocked: false },
        helium3: { cur: 0, max: 5, unlocked: false },
        antimatter: { cur: 0, max: 5, unlocked: false }
    },
    pop: {
        total: 0, idle: 0,
        farmer: 0, woodcutter: 0, scholar: 0, mason: 0, digger: 0, hunter: 0,
        miner: 0, blacksmith: 0, smelter: 0, priest: 0,
        carpenter: 0, brickmaker: 0, glassblower: 0, wizard: 0, alchemist: 0, metalworker: 0,
        scribe: 0, brewer: 0, armorsmith: 0, knight: 0, inquisitor: 0, weaponsmith: 0,
        chemist: 0, musketeer: 0, painter: 0, navigator: 0, banker: 0, weaver: 0,
        driller: 0, factoryworker: 0, engineer: 0, operator: 0, capitalist: 0, tapper: 0,
        nucleartech: 0, synthesizer: 0, geneticist: 0, aiarchitect: 0, miner_uranium: 0,
        refiner: 0, nanobuilder: 0, physicist: 0
    },
    bld: {
        hut: { count: 0, base: { wood: 50 }, mult: 1.15 }, 
        stockpile: { count: 0, base: { wood: 30 }, mult: 1.15 }, 
        granary: { count: 0, base: { wood: 100 }, mult: 1.15 }, 
        warehouse: { count: 0, base: { wood: 150, stone: 20 }, mult: 1.15 },
        vault: { count: 0, base: { stone: 200, wood: 100 }, mult: 1.15 }, 
        house: { count: 0, base: { wood: 100, stone: 20 }, mult: 1.15 },
        library: { count: 0, base: { wood: 200, stone: 50 }, mult: 1.15 }, 
        temple: { count: 0, base: { stone: 300 }, mult: 1.15 }, 
        pyramid: { count: 0, base: { stone: 2000, gold: 400 }, mult: 1.0 },
        sawmill: { count: 0, base: { lumber: 50, wood: 200 }, mult: 1.15 }, 
        glassworks: { count: 0, base: { brick: 100, glass: 50 }, mult: 1.15 }, 
        academy: { count: 0, base: { brick: 200, glass: 100 }, mult: 1.15 }, 
        magetower: { count: 0, base: { brick: 300, mana: 50 }, mult: 1.15 }, 
        colosseum: { count: 0, base: { stone: 1000, brick: 500 }, mult: 1.15 }, 
        parthenon: { count: 0, base: { lumber: 2000, brick: 2000, gold: 800 }, mult: 1.0 },
        castle: { count: 0, base: { stone: 2000, lumber: 1000 }, mult: 1.15 }, 
        cathedral: { count: 0, base: { stone: 3000, glass: 1000, faith: 2000 }, mult: 1.15 }, 
        barracks: { count: 0, base: { lumber: 500, stone: 500 }, mult: 1.15 }, 
        scriptorium: { count: 0, base: { lumber: 300, parchment: 100 }, mult: 1.15 }, 
        grandcathedral: { count: 0, base: { glass: 2000, stone: 4000, faith: 2000, chivalry: 400 }, mult: 1.0 },
        bank: { count: 0, base: { brick: 1000, gold: 500 }, mult: 1.15 }, 
        museum: { count: 0, base: { brick: 800, art: 200 }, mult: 1.15 }, 
        shipyard: { count: 0, base: { lumber: 2000, canvas: 500 }, mult: 1.15 }, 
        observatory: { count: 0, base: { glass: 500, brass: 200 }, mult: 1.15 }, 
        printingpress: { count: 0, base: { lumber: 400, parchment: 300 }, mult: 1.15 }, 
        globetheatre: { count: 0, base: { lumber: 3200, art: 1200, influence: 800 }, mult: 1.0 },
        oilrig: { count: 0, base: { steel: 2000, engines: 500 }, mult: 1.15 }, 
        powerplant: { count: 0, base: { steel: 3000, coal: 5000 }, mult: 1.15 }, 
        factory: { count: 0, base: { steel: 2500, concrete: 1000 }, mult: 1.15 }, 
        skyscraper: { count: 0, base: { steel: 5000, concrete: 10000 }, mult: 1.15 }, 
        railroad: { count: 0, base: { steel: 4000, lumber: 2000 }, mult: 1.15 }, 
        eiffeltower: { count: 0, base: { steel: 6000, concrete: 3200, engines: 800 }, mult: 1.0 },
        nuclearreactor: { count: 0, base: { superalloy: 1000, concrete: 5000 }, mult: 1.15 }, 
        launchpad: { count: 0, base: { concrete: 10000, steel: 8000 }, mult: 1.15 }, 
        cryochamber: { count: 0, base: { superalloy: 500, power: 5000 }, mult: 1.15 }, 
        hadroncollider: { count: 0, base: { superalloy: 3000, power: 10000 }, mult: 1.15 }, 
        spaceelevator: { count: 0, base: { superalloy: 20000, nanobots: 4000, antimatter: 400 }, mult: 1.0 }
    },
    tech: {
        stoneTools: { researched: false, cost: 20 },
        mining: { researched: false, cost: 100 },
        construction: { researched: false, cost: 150 },
        smelting: { researched: false, cost: 300 },
        steelwork: { researched: false, cost: 600 },
        mysticism: { researched: false, cost: 1000 },
        monumentalism: { researched: false, cost: 5000 },
        mathematics: { researched: false, cost: 2000 },
        engineering: { researched: false, cost: 4000 },
        glassblowing: { researched: false, cost: 6000 },
        currency: { researched: false, cost: 8000 },
        drama: { researched: false, cost: 10000 },
        magic: { researched: false, cost: 15000 },
        alchemy: { researched: false, cost: 25000 },
        metalworking: { researched: false, cost: 30000 },
        divineright: { researched: false, cost: 50000 },
        feudalism: { researched: false, cost: 75000 },
        chivalrycode: { researched: false, cost: 100000 },
        manuscript: { researched: false, cost: 120000 },
        brewing: { researched: false, cost: 150000 },
        platearmor: { researched: false, cost: 200000 },
        inquisition: { researched: false, cost: 250000 },
        gothicarch: { researched: false, cost: 500000 },
        exploration: { researched: false, cost: 600000 },
        gunpowdertech: { researched: false, cost: 750000 },
        banking: { researched: false, cost: 900000 },
        artistry: { researched: false, cost: 1100000 },
        navigation: { researched: false, cost: 1300000 },
        printing: { researched: false, cost: 1500000 },
        humanism: { researched: false, cost: 2000000 },
        steelframe: { researched: false, cost: 2500000 },
        petroleum: { researched: false, cost: 3000000 },
        electricity: { researched: false, cost: 3500000 },
        assembly: { researched: false, cost: 4000000 },
        combustion: { researched: false, cost: 5000000 },
        capitalism: { researched: false, cost: 6000000 },
        modernarch: { researched: false, cost: 8000000 },
        nuclear: { researched: false, cost: 4000000 },
        rocketry: { researched: false, cost: 4800000 },
        nanotechnology: { researched: false, cost: 6000000 },
        genetics: { researched: false, cost: 7200000 },
        ai: { researched: false, cost: 8000000 },
        antimatterphysics: { researched: false, cost: 12000000 },
        spacecolonization: { researched: false, cost: 20000000 }
    },
    stats: {
        totalResourcesGathered: 0,
        manualClicks: 0,
        buildingsConstructed: 0,
        techResearched: 0,
        villagersRecruited: 0,
        timePlayed: 0,
        eraReached: 0,
        achievementsUnlocked: 0
    },
    achievements: {},
    lastSaveTime: Date.now()
};

// Initialize achievements state based on config
for(let key in ACHIEVEMENTS) {
    G.achievements[key] = false;
}